services:
  - type: web
    name: talking-head-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd app && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: D_ID_API_KEY
        sync: false
      - key: D_ID_BASE_URL
        value: https://api.d-id.com
      - key: PYTHON_VERSION
        value: 3.12.5
